### ISSUE TITLE
ModuleNotFoundError: No module named 'special_characters'

### ISSUE THREAD

**Issue by Dr1zz3l** [MariosGkMeng/Straightforward-Obsidian2Latex#2]
I absolutely love what you are trying to achieve here. I'm pretty much in need of the same thing. Especially your support of embedded content [[like this]] is amazing.

However, executing converter.py just gives me:
```
Straightforward-Obsidian2Latex-main\src\embedded_notes.py", line 11, in <module>
    from special_characters import *
ModuleNotFoundError: No module named 'special_characters'
```

I assume you're missing a file "special_characters.py" in your main branch?

**Comment by MariosGkMeng** [comment]
Hello! 

Thank you for your appreciation! Exactly, this is one of the main reasons I created this repo! 

Yes, you are right, there was an issue with this file and it was not in the branch, now it is. 

I have made a few additions those last few days, so I need to update the example vault (the code is updated).
